export enum QuoteStatus {
  OPEN = 'OPEN',
  RESPONDED = 'RESPONDED',
  ACCEPTED = 'ACCEPTED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum ResponseStatus {
  ACTIVE = 'ACTIVE',
  WITHDRAWN = 'WITHDRAWN',
  SELECTED = 'SELECTED',
  REJECTED = 'REJECTED',
}
